#
#  SPDX-License-Identifier: Apache-2.0
#
#  Copyright The original authors
#
#  Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.7
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.7
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
   image: debezium/connect-base:1.7
   ports:
    - 8083:8083
   links:
    - kafka
   volumes:
    - ./basic-auth:/kafka/config/basic-auth
   environment:
    - BOOTSTRAP_SERVERS=kafka:9092
    - GROUP_ID=1
    - CONFIG_STORAGE_TOPIC=my_connect_configs
    - OFFSET_STORAGE_TOPIC=my_connect_offsets
    - STATUS_STORAGE_TOPIC=my_connect_statuses

    #  Add the basic auth extension
    - CONNECT_REST_EXTENSION_CLASSES=org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
    
    #  Set the login config:
    #  - see ./basic-auth/jaas.config for basic auth configuration
    #  - see ./basic-auth/connect.password for credentials
    - KAFKA_OPTS=-Djava.security.auth.login.config=/kafka/config/basic-auth/jaas.config